#ifndef BOARD_WAVESHARE_PHOTOPAINTER_73_H
#define BOARD_WAVESHARE_PHOTOPAINTER_73_H

#include "driver/gpio.h"

// Board Info
#define BOARD_HAL_NAME "waveshare_photopainter_73"
#define BOARD_HAL_TYPE BOARD_TYPE_WAVESHARE_PHOTOPAINTER

// Button Definitions
#define BOARD_HAL_WAKEUP_KEY GPIO_NUM_0  // BOOT button
#define BOARD_HAL_ROTATE_KEY GPIO_NUM_4  // Usage: Wakeup + Rotate
#define BOARD_HAL_CLEAR_KEY GPIO_NUM_NC  // Not supported

// SPI Pins
#define BOARD_HAL_SPI_SCLK_PIN GPIO_NUM_10
#define BOARD_HAL_SPI_MOSI_PIN GPIO_NUM_11
#define BOARD_HAL_SPI_MISO_PIN GPIO_NUM_NC

// E-Paper Display Pins (Spectra E6)
#define BOARD_HAL_EPD_DC_PIN GPIO_NUM_8
#define BOARD_HAL_EPD_CS_PIN GPIO_NUM_9
#define BOARD_HAL_EPD_RST_PIN GPIO_NUM_12
#define BOARD_HAL_EPD_BUSY_PIN GPIO_NUM_13

// SD Card Pins (SDIO 4-bit)
#define BOARD_HAL_SD_CLK_PIN GPIO_NUM_39
#define BOARD_HAL_SD_CMD_PIN GPIO_NUM_41
#define BOARD_HAL_SD_D0_PIN GPIO_NUM_40
#define BOARD_HAL_SD_D1_PIN GPIO_NUM_1
#define BOARD_HAL_SD_D2_PIN GPIO_NUM_2
#define BOARD_HAL_SD_D3_PIN GPIO_NUM_38

// Display Configuration
#define BOARD_HAL_DISPLAY_ROTATION_DEG 180

#endif  // BOARD_WAVESHARE_PHOTOPAINTER_73_H
